version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://zander.digital/api
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DOCKERIZED: "1"
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: 5000
      FLASK_DEBUG: "True"
      FLASK_THREADED: "True"
      RESTPLUS_SWAGGER_EXPANSION: "list"
      RESTPLUS_VALIDATE: "True"
      RESTPLUS_MASK_SWAGGER: "False"
      CORS_ORIGINS: "https://zander.digital"
      SQLALCHEMY_DATABASE_URI: ""
      SQLALCHEMY_TRACK_MODS: "False"
